### ISSUE TITLE
Process dataset

### ISSUE THREAD

**Issue by TerryMelody** [AstraZeneca/MCPL#2]
Dear authors, in the class PersonalizedBase, should we process the dataset you provided? I don't know what to assign for data_root.

**Comment by lxasqjc** [comment]
Hi, it could be either your own or the provided data path e.g. '--data_root ./dataset/natural_2_concepts/teddybear_skateboard/unmasked/0'

**Comment by TerryMelody** [comment]
> teddybear_skateboard

Thanks a lot!
